config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  root "quotes#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :name, presence: true
    scope :ordered, -> { order(id: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action -> { sleep 3 }
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)
      if @quote.save
        respond_to do |format|
          format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
          format.turbo_stream
        end
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      # format.json { head :no_content }
      format.turbo_stream

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditorTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class=" prose mx-auto">
    <main class=" mx-auto mt-28 px-5 ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class= "text-center">
    <span>
      <%= form.label :name,
       style: "display: block, color: #26b72b" ,
       class:"visibility: hidden" %>
      <%= form.text_field :name %>
    </span>

    <span class= " text-white no-underline font-semibold bg-blue-400 hover:bg-blue-700 rounded py-2 px-2 mx-auto w-28 text-center text-xs">
      <%= form.submit %>
    </span>
  </div>
  <br>
  
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <span class="flex bg-transparent text-blue-700 font-semibold hover:text-white py-4 px-4 border border-blue-500 hover:border-transparent hover:bg-blue-200 hover: delay-200 rounded m-2 ">
    
    <%= link_to "#{quote.name}",
        quote_path(quote),
        data: { turbo_frame: "_top" },
        class:" truncate text-blue-400 no-underline px-3 w-96 ; " %>
  
    <div class="quote__actions grow flex justify-end">
      <%= button_to "Delete",
          quote_path(quote),
          method: :delete,
          form: { data: { turbo_frame: "_top" } },
          class: " bg-transparent text-white no-underline font-semibold bg-blue-400 hover:bg-transparent hover:text-blue-700 rounded p-2 mx-2 " %>

      <%= link_to "Edit" ,
          edit_quote_path(quote),
          class: " bg-transparent text-white no-underline font-semibold bg-blue-400 hover:bg-transparent hover:text-blue-700 rounded p-2 mx-2 " %>
    </div>

  </span>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>
<%= turbo_frame_tag @quote do %>
  <%= render "form", quote: @quote %>
<% end %>

<br>

<div>
  <%= link_to "Show this quote", @quote, class: "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %> |
  <%= link_to "Back to quotes", quotes_path, class: "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag "F1" do %>
  <h1 class ="flex text-blue-400 justify-center">Quotes</h1>
  <%= link_to "New quote",
      new_quote_path,
      data: { turbo_frame: dom_id(Quote.new) },
      class: "flex items-center justify-center no-underline text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2  " %>
<% end %>

<%= turbo_frame_tag Quote.new %>

<%= turbo_frame_tag "quotes" do %>
  <div id="quotes">
    <%= render @quotes %>
  </div>
<% end %>

app/views/quotes/new.html.erb
<h1>New quote</h1>
  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
<br>

<div>
  <%= link_to "Back to quotes", quotes_path, class: "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

  <%= link_to "Back to quotes",
      quotes_path,
      class: " text-white no-underline font-semibold bg-blue-400 hover:bg-transparent hover:text-blue-700 rounded p-2 mx-2 "
  %>
<!--
<div>
  <%= link_to "Edit",
      edit_quote_path(@quote),
      class: " text-white no-underline font-semibold bg-blue-400 hover:bg-transparent hover:text-blue-700 rounded p-2 mx-2 "
  %>
  |

   <%= button_to "Destroy this quote", @quote, method: :delete %> 
</div>
  -->